CONFIG_NAME: 'DMGAN'

DATASET_NAME: 'birds'
DATA_DIR: '../data/birds'
GPU_ID: 0
WORKERS: 4


TREE:
    BRANCH_NUM: 3

TRAIN:
    FLAG: True
    NET_G: ''  # '../models/bird_AttnGAN2.pth'
    B_NET_D: True
    BATCH_SIZE: 10  # 22
    MAX_EPOCH: 800
    SNAPSHOT_INTERVAL: 25
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002
    #
    NET_E: '../DAMSMencoders/bird/text_encoder.pth'
    SMOOTH:
        GAMMA1: 4.0  # 1,2,5 good 4 best  10&100bad
        GAMMA2: 5.0
        GAMMA3: 10.0  # 10good 1&100bad
        LAMBDA: 5.0
        LAMBDA1: 10.0

CAP:
    embed_size: 256
    hidden_size: 256
    num_layers: 1
    learning_rate: 0.001
    caption_cnn_path: '../data/STREAM/cnn_encoder.ckpt'
    caption_rnn_path: '../data/STREAM/rnn_decoder.ckpt'

GAN:
    DF_DIM: 32
    GF_DIM: 64
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
